from .signup import *
from .home import *
from .category import CategoryView
from .product import ProductView
from .checkout import checkout,quick_order
from .departaments import city,departament,load_departaments
from .search import search
from .orders import orders,OrderView
from .user import profile,favorites