from .brand import BrandAdmin
from .category import CategoryAdmin
from .offer import OfferAdmin
from .popular import PopularAdmin
from .product import ProductAdmin,Add_ModelAdmin
from .special import SpecialAdmin
from .storage import StorageAdmin
from .attribute import AttributeAdmin
from .tag import TagAdmin
from .prom import PromAdmin
from .gallery import GalleryAdmin
from .city import CityAdmin
from .page import PageAdmin
from .percent import PercentAdmin
from .featured import FeaturedAdmin
from .tigres import TigresCategoryAdmin,TigresAdmin
from .google import GoogleFeedAdmin
from .currency import CurrencyAdmin
from .export import ExportAdmin