from .index import *
from .prices import *
from .stock import *
from .add import *
from .edit import EditView
from .list import List
from .search import search
from .departaments import city,departaments
from .gallery import ordering
from .autocomplete import autocomplete
from .database import change_database
from .action import action,product_export,product_update_export,availability
from .REST import *