from transliterate.base import TranslitLanguagePack, registry
from transliterate import translit,get_available_language_codes

class UkrainskiyLanguagePack(TranslitLanguagePack):
    language_code = "uk"
    language_name = "Ukrainskiy"
    mapping = (
        u"абвгґдеєжзиіїйклмнопрстуфхцчшщьюяы",
        u"abvggdeejziiyyklmnoprstufhchshsh'yuyai",
    )
    pre_processor_mapping = {
        u'а':u'a',
        u'б':u'b',
        u'в':u'v',
        u'г':u'g',
        u'ґ':u'g',
        u'д':u'd',
        u'е':u'e',
        u'є':u'e',
        u'ж':u'j',
        u'з':u'z',
        u'и':u'i',
        u'і':u'i',
        u'ї':u'yi',
        u'й':u'y',
        u'к':u'k',
        u'л':u'l',
        u'м':u'm',
        u'н':u'n',
        u'о':u'o',
        u'п':u'p',
        u'р':u'r',
        u'с':u's',
        u'т':u't',
        u'у':u'u',
        u'ф':u'f',
        u'х':u'h',
        u'ц':u'c',
        u'ч':u'ch',
        u'ш':u'sh',
        u'щ':u"sh'",
        u'ь':u"'",
        u'ю':u'yu',
        u'я':u'ya',
        u'ы':u'i',
        u' ':'-',
        u'А':'A',
        u'Б':'B',
        u'В':'V',
        u'Г':'G',
        u'Ґ':'G',
        u'Д':'D',
        u'Е':'E',
        u'Є':'E',
        u'Ж':'J',
        u'З':'Z',
        u'И':'I',
        u'І':'I',
        u'Ї':'Yi',
        u'Й':'Y',
        u'К':'K',
        u'Л':'L',
        u'М':'M',
        u'Н':'N',
        u'О':'O',
        u'П':'P',
        u'Р':'R',
        u'С':'S',
        u'Т':'T',
        u'У':'U',
        u'Ф':'F',
        u'Х':'H',
        u'Ц':'C',
        u'Ч':'Ch',
        u'Ш':'Sh',
        u'Щ':"Sh'",
        u'Ь':"'",
        u'Ю':'Yu',
        u'Я':'Ya',
    }

registry.register(UkrainskiyLanguagePack,force=True)